name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Make ci
      run: |
        mkdir -p $GOPATH/src/github.com/bytom
        mv ../bytom $GOPATH/src/github.com/bytom
        cd $GOPATH/src/github.com/bytom
        make ci

    - name: Build
      run: go build -v .
